### ISSUE TITLE
how to run this application?

### ISSUE THREAD

**Issue by snowch** [doublerebel/cloudant-user#1]
The usage instructions provide some sort of script, but how is this script run?

Presumably:

```
# first install node.js, then:
npm install -g coffee-script
git clone https://github.com/doublerebel/cloudant-user.git
cd cloudant-user
edit somefile ???
cake ???
```

**Comment by doublerebel** [comment]
@snowch I've updated the README to add more examples and explanation.  Please take a look and let me know if you have more questions.
